# Generated by Django 3.1.2 on 2020-11-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masruri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[
                 ('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
                ('description', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('tag', models.ManyToManyField(to='masruri.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), (
                    'Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('custumer', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='masruri.custumer')),
                ('product', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='masruri.product')),
            ],
        ),
    ]
